services:
  frontend:
    image: dividis-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file: .env
    restart: unless-stopped
    networks:
      - dividis_network

networks:
  dividis_network:
    external: true
