services:
  frontend:
    image: dividis-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file: .env.docker
    restart: unless-stopped
    volumes:
      - ./public:/app/public:ro
      - ./src:/app/src:ro
    networks:
      - dividis_network

networks:
  dividis_network:
   external: true
